/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package slavko.baze2.procesnabavke.gui.forme.glavna;

import slavko.baze2.procesnabavke.gui.forme.zaposleni.PanelPrijavljivanjeZaposlenog;
import slavko.baze2.procesnabavke.gui.domen.Zaposleni;
import slavko.baze2.procesnabavke.gui.forme.proizvod.PanelPretragaProizvoda;
import slavko.baze2.procesnabavke.gui.forme.proizvod.PanelRadSaProizvodom;
import slavko.baze2.procesnabavke.gui.forme.faktura.PanelPretragaFaktura;
import slavko.baze2.procesnabavke.gui.forme.faktura.PanelRadSaFakturom;
import java.awt.BorderLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.springframework.beans.factory.annotation.Autowired;
import slavko.baze2.procesnabavke.gui.poslovnalogika.Kontroler;
import slavko.baze2.procesnabavke.services.ProizvodService;

/**
 *
 * @author Slavko
 */
public class FrmGlavna extends javax.swing.JFrame {

    @Autowired
    private ProizvodService proizvodService;

    /**
     * Creates new form FrmGlavna
     */
    public FrmGlavna() {
        initComponents();
        srediFormu();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblDobrodošli = new javax.swing.JLabel();
        jlblImePrezime = new javax.swing.JLabel();
        jbtnPrijavljivanje = new javax.swing.JButton();
        jmbGlavniMeni = new javax.swing.JMenuBar();
        jmUpravljanjeFakturama = new javax.swing.JMenu();
        jmiPregledFaktura = new javax.swing.JMenuItem();
        jmiUnosFakture = new javax.swing.JMenuItem();
        jmUpravljanjeProizvodima = new javax.swing.JMenu();
        jmiPregledProizvoda = new javax.swing.JMenuItem();
        jmiUnosProizvoda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(540, 260));
        setMinimumSize(new java.awt.Dimension(540, 260));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblDobrodošli.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblDobrodošli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblDobrodošli.setText("DOBRODOŠLI");
        getContentPane().add(jlblDobrodošli, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 540, -1));

        jlblImePrezime.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jlblImePrezime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblImePrezime.setText("Ime Prezime");
        getContentPane().add(jlblImePrezime, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 540, -1));

        jbtnPrijavljivanje.setText("PRIJAVLJIVANJE");
        jbtnPrijavljivanje.setAlignmentX(1.0F);
        jbtnPrijavljivanje.setAlignmentY(3.0F);
        jbtnPrijavljivanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrijavljivanjeActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPrijavljivanje, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 140, 50));

        jmUpravljanjeFakturama.setText("Upravljanje fakturama");

        jmiPregledFaktura.setText("Pregled");
        jmiPregledFaktura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPregledFakturaActionPerformed(evt);
            }
        });
        jmUpravljanjeFakturama.add(jmiPregledFaktura);

        jmiUnosFakture.setText("Unos");
        jmiUnosFakture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosFaktureActionPerformed(evt);
            }
        });
        jmUpravljanjeFakturama.add(jmiUnosFakture);

        jmbGlavniMeni.add(jmUpravljanjeFakturama);

        jmUpravljanjeProizvodima.setText("Upravljanje proizvodima");

        jmiPregledProizvoda.setText("Pregled");
        jmiPregledProizvoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPregledProizvodaActionPerformed(evt);
            }
        });
        jmUpravljanjeProizvodima.add(jmiPregledProizvoda);

        jmiUnosProizvoda.setText("Unos");
        jmiUnosProizvoda.setToolTipText("");
        jmiUnosProizvoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosProizvodaActionPerformed(evt);
            }
        });
        jmUpravljanjeProizvodima.add(jmiUnosProizvoda);

        jmbGlavniMeni.add(jmUpravljanjeProizvodima);

        setJMenuBar(jmbGlavniMeni);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiUnosProizvodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosProizvodaActionPerformed
        otvoriDialog("Unos proizvoda", new PanelRadSaProizvodom());
    }//GEN-LAST:event_jmiUnosProizvodaActionPerformed

    private void jmiPregledProizvodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPregledProizvodaActionPerformed
        otvoriDialog("Pregled proizvoda", new PanelPretragaProizvoda());
    }//GEN-LAST:event_jmiPregledProizvodaActionPerformed

    private void jmiUnosFaktureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosFaktureActionPerformed
        otvoriDialog("Unos fakture", new PanelRadSaFakturom());
    }//GEN-LAST:event_jmiUnosFaktureActionPerformed

    private void jmiPregledFakturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPregledFakturaActionPerformed
        otvoriDialog("Pregled faktura", new PanelPretragaFaktura());
    }//GEN-LAST:event_jmiPregledFakturaActionPerformed

    private void jbtnPrijavljivanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrijavljivanjeActionPerformed
        System.out.println("Autowiring: " + proizvodService);

        if (jbtnPrijavljivanje.getText().equals("Odjavljivanje")) {
            slavko.baze2.procesnabavke.gui.util.Util.vratiInstancu().obriši("prijavljeni_korisnik");
            srediFormu();
        } else {
            JDialog dialog = otvoriDialog("Prijavljivanje zaposlenog", new PanelPrijavljivanjeZaposlenog());
            dialog.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    srediFormu();
                }
            });
        }
    }//GEN-LAST:event_jbtnPrijavljivanjeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGlavna().setVisible(true);
            }
        });
    }

    private JDialog otvoriDialog(String naziv, JPanel panel) {
        JDialog dialog = new JDialog(this, naziv, true);
        dialog.setLayout(new BorderLayout());
        dialog.add(panel, BorderLayout.CENTER);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        return dialog;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnPrijavljivanje;
    private javax.swing.JLabel jlblDobrodošli;
    private javax.swing.JLabel jlblImePrezime;
    private javax.swing.JMenu jmUpravljanjeFakturama;
    private javax.swing.JMenu jmUpravljanjeProizvodima;
    private javax.swing.JMenuBar jmbGlavniMeni;
    private javax.swing.JMenuItem jmiPregledFaktura;
    private javax.swing.JMenuItem jmiPregledProizvoda;
    private javax.swing.JMenuItem jmiUnosFakture;
    private javax.swing.JMenuItem jmiUnosProizvoda;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        Zaposleni zaposleni = (Zaposleni) slavko.baze2.procesnabavke.gui.util.Util.vratiInstancu().vrati("prijavljeni_korisnik");
        if (zaposleni != null) {
            jlblDobrodošli.setVisible(true);
            jlblImePrezime.setText(zaposleni.toString());
            jlblImePrezime.setVisible(true);
            jmiPregledFaktura.setEnabled(true);
            jmiPregledProizvoda.setEnabled(true);
            jmiUnosFakture.setEnabled(true);
            jmiUnosProizvoda.setEnabled(true);
            jbtnPrijavljivanje.setText("Odjavljivanje");
        } else {
            jlblDobrodošli.setVisible(false);
            jlblImePrezime.setVisible(false);
            jmiPregledFaktura.setEnabled(false);
            jmiPregledProizvoda.setEnabled(false);
            jmiUnosFakture.setEnabled(false);
            jmiUnosProizvoda.setEnabled(false);
            jbtnPrijavljivanje.setText("Prijavljivanje");
        }
    }
}
