/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package slavko.baze2.procesnabavke.gui.forme.zaposleni;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Service;
import slavko.baze2.procesnabavke.gui.domen.Zaposleni;
import slavko.baze2.procesnabavke.services.ZaposleniService;

import javax.swing.*;
import org.springframework.stereotype.Component;

/**
 *
 * @author Slavko
 */
@Component
@Scope(value = "prototype")
public class PanelPrijavljivanjeZaposlenog extends javax.swing.JPanel {

    @Autowired
    private ZaposleniService zaposleniService;

    /**
     * Creates new form PanelPrijavljivanjeZaposlenog
     */
    public PanelPrijavljivanjeZaposlenog() {
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtKorisničkoIme = new javax.swing.JTextField();
        jlblKorisničkoImeMandatory = new javax.swing.JLabel();
        jlblŠifraMandatory = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jtxtŠifra = new javax.swing.JPasswordField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Šifra:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Korisničko Ime:");

        jtxtKorisničkoIme.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jlblKorisničkoImeMandatory.setForeground(new java.awt.Color(255, 0, 0));
        jlblKorisničkoImeMandatory.setText("*");

        jlblŠifraMandatory.setForeground(new java.awt.Color(255, 0, 0));
        jlblŠifraMandatory.setText("*");

        jButton1.setText("Prijavi se");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jtxtKorisničkoIme, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                                        .addComponent(jtxtŠifra)))
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlblKorisničkoImeMandatory, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlblŠifraMandatory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jtxtKorisničkoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlblKorisničkoImeMandatory))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlblŠifraMandatory)
                                        .addComponent(jtxtŠifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String korisničkoIme = jtxtKorisničkoIme.getText();
        String šifra = new String(jtxtŠifra.getPassword());
        boolean formValid = true;

        if (korisničkoIme.isEmpty() || korisničkoIme == null) {
            jlblKorisničkoImeMandatory.setVisible(true);
            formValid = false;
        } else {
            jlblKorisničkoImeMandatory.setVisible(false);
        }
        if (šifra.isEmpty() || šifra == null) {
            jlblŠifraMandatory.setVisible(true);
            formValid = false;
        } else {
            jlblŠifraMandatory.setVisible(false);
        }

        if (!formValid) {
            return;
        }

        try {
            Zaposleni zaposleni = zaposleniService.getByUsernameAndPassword(korisničkoIme, šifra);
            if (zaposleni == null) {
                JOptionPane.showMessageDialog(this, "Sistem nije uspeo da nađe zaposlenog sa zadatim kredencijalima", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            slavko.baze2.procesnabavke.gui.util.Util.vratiInstancu().postavi("prijavljeni_korisnik", zaposleni);
            JOptionPane.showMessageDialog(this, "Uspešno prijavljivanje", "Prijavljivanje", JOptionPane.INFORMATION_MESSAGE);
            ((JDialog) SwingUtilities.getWindowAncestor(this)).dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlblKorisničkoImeMandatory;
    private javax.swing.JLabel jlblŠifraMandatory;
    private javax.swing.JTextField jtxtKorisničkoIme;
    private javax.swing.JPasswordField jtxtŠifra;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        jlblKorisničkoImeMandatory.setVisible(false);
        jlblŠifraMandatory.setVisible(false);
    }


}
