/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package slavko.baze2.procesnabavke.gui.forme.proizvod;

import org.springframework.beans.factory.BeanFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import slavko.baze2.procesnabavke.gui.domen.Proizvod;
import slavko.baze2.procesnabavke.gui.forme.proizvod.model.ProizvodTableModel;
import slavko.baze2.procesnabavke.services.ProizvodService;

import javax.annotation.PostConstruct;
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Slavko
 */
@Component
@Scope(value = "prototype")
public class PanelPretragaProizvoda extends javax.swing.JPanel {

    /**
     * Creates new form PanelPretragaProizvoda
     */

    @Autowired
    private BeanFactory beanFactory;
    @Autowired
    private ProizvodService proizvodService;

    public PanelPretragaProizvoda() {
        initComponents();
    }

    @PostConstruct
    public void setUp() {
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblProizvodi = new javax.swing.JTable();
        jbtnDetaljiProizvod = new javax.swing.JButton();
        jbtnObrisiProizvod = new javax.swing.JButton();

        jtblProizvodi.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane1.setViewportView(jtblProizvodi);

        jbtnDetaljiProizvod.setText("Detalji");
        jbtnDetaljiProizvod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDetaljiProizvodActionPerformed(evt);
            }
        });

        jbtnObrisiProizvod.setText("Obriši proizvod");
        jbtnObrisiProizvod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiProizvodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(jbtnDetaljiProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jbtnObrisiProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jbtnDetaljiProizvod)
                                        .addComponent(jbtnObrisiProizvod))
                                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDetaljiProizvodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDetaljiProizvodActionPerformed
        if (jtblProizvodi.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Morate selektovati proizvod u tabeli!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        slavko.baze2.procesnabavke.gui.util.Util.vratiInstancu().postavi("izabrani_proizvod", ((ProizvodTableModel) jtblProizvodi.getModel()).getProizvod(jtblProizvodi.getSelectedRow()));
        JDialog dialog = new JDialog((JDialog) SwingUtilities.getWindowAncestor(this), "Izmena proizvoda", true);
        dialog.setLayout(new BorderLayout());
        dialog.add(beanFactory.getBean(PanelRadSaProizvodom.class), BorderLayout.CENTER);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_jbtnDetaljiProizvodActionPerformed

    private void jbtnObrisiProizvodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiProizvodActionPerformed
        if (jtblProizvodi.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Morate selektovati proizvod u tabeli!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ProizvodTableModel ptm = ((ProizvodTableModel) jtblProizvodi.getModel());
        Proizvod proizvod = ptm.getProizvod(jtblProizvodi.getSelectedRow());
        try {
            proizvodService.delete(proizvod.getSifra());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ptm.obrisiRed(jtblProizvodi.getSelectedRow());
        JOptionPane.showMessageDialog(this, "Sistem je obrisao proizvod", "Brisanje proizvoda", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jbtnObrisiProizvodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDetaljiProizvod;
    private javax.swing.JButton jbtnObrisiProizvod;
    private javax.swing.JTable jtblProizvodi;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        List<Proizvod> lp = new ArrayList<>();
        try {
            lp = proizvodService.getAll();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        jtblProizvodi.setModel(new ProizvodTableModel(lp));
    }

}
