/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package slavko.baze2.procesnabavke.gui.forme.proizvod;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import slavko.baze2.procesnabavke.gui.domen.Proizvod;
import slavko.baze2.procesnabavke.gui.util.Util;
import slavko.baze2.procesnabavke.services.ProizvodService;

import javax.swing.*;
import javax.swing.text.NumberFormatter;
import java.text.NumberFormat;
import org.springframework.context.annotation.Scope;

/**
 *
 * @author Slavko
 */
@Component
@Scope(value = "prototype")
public class PanelRadSaProizvodom extends javax.swing.JPanel {

    @Autowired
    private ProizvodService proizvodService;

    /**
     * Creates new form PanelRadSaProizvodom
     */
    private Proizvod izabraniProizvod;

    public PanelRadSaProizvodom() {
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtBrProizvoda = new javax.swing.JTextField();
        jtxtNazivProizvoda = new javax.swing.JTextField();
        jlblNazivProizvodaValidator = new javax.swing.JLabel();
        jlblSifraProizvodaValidator = new javax.swing.JLabel();
        sacuvajButton = new javax.swing.JButton();
        izmeniButton = new javax.swing.JButton();

        setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setText("Naziv proizvoda:");

        jLabel4.setText("Sifra proizvoda");

        jtxtBrProizvoda.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxtBrProizvoda.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtxtBrProizvoda.setEnabled(false);

        jlblNazivProizvodaValidator.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblNazivProizvodaValidator.setForeground(new java.awt.Color(255, 0, 0));
        jlblNazivProizvodaValidator.setText("*");

        jlblSifraProizvodaValidator.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblSifraProizvodaValidator.setForeground(new java.awt.Color(255, 0, 0));
        jlblSifraProizvodaValidator.setText("*");

        sacuvajButton.setText("Sacuvaj");
        sacuvajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sacuvajButtonActionPerformed(evt);
            }
        });

        izmeniButton.setText("Izmeni");
        izmeniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izmeniButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtBrProizvoda)
                            .addComponent(jtxtNazivProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblNazivProizvodaValidator, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblSifraProizvodaValidator, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(izmeniButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sacuvajButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBrProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblSifraProizvodaValidator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jlblNazivProizvodaValidator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jtxtNazivProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sacuvajButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(izmeniButton)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sacuvajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sacuvajButtonActionPerformed
       sacuvajProizvod();
    }//GEN-LAST:event_sacuvajButtonActionPerformed

    private void izmeniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izmeniButtonActionPerformed
        izmeniProizvod();
    }//GEN-LAST:event_izmeniButtonActionPerformed

    private void sacuvajProizvod(){
    if (!validirajUnosProizvoda()) {
            return;
        }

        String naziv = jtxtNazivProizvoda.getText();
        Long sifra = Long.parseLong(jtxtBrProizvoda.getText());

        try {
            Proizvod proizvod = new Proizvod.Builder()
                    .withSifra(sifra)
                    .withNaziv(naziv).build();
            proizvodService.create(proizvod);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }

        JOptionPane.showMessageDialog(this, "Sistem je zapamtio proizvod", "Čuvanje proizvoda", JOptionPane.INFORMATION_MESSAGE);}
    
    private void izmeniProizvod(){
        if (!validirajUnosProizvoda()) {
            return;
        }

        String naziv = jtxtNazivProizvoda.getText();
        izabraniProizvod.setNaziv(naziv);

        try {
            proizvodService.update(izabraniProizvod.getSifra(), izabraniProizvod);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(this, "Sistem je zapamtio proizvod", "Izmena proizvoda", JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton izmeniButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jlblNazivProizvodaValidator;
    private javax.swing.JLabel jlblSifraProizvodaValidator;
    private javax.swing.JTextField jtxtBrProizvoda;
    private javax.swing.JTextField jtxtNazivProizvoda;
    private javax.swing.JButton sacuvajButton;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        jlblSifraProizvodaValidator.setVisible(false);
        jlblNazivProizvodaValidator.setVisible(false);

        izabraniProizvod = (Proizvod) Util.vratiInstancu().vrati("izabrani_proizvod");
        if (izabraniProizvod != null) {
            // Operacija promena proizvoda                
            sacuvajButton.setVisible(false);
            izmeniButton.setVisible(true);
            jtxtBrProizvoda.setEnabled(false);
            jtxtBrProizvoda.setEditable(false);

            jtxtBrProizvoda.setText(izabraniProizvod.getSifra().toString());
            jtxtNazivProizvoda.setText(izabraniProizvod.getNaziv());
            Util.vratiInstancu().obriši("izabrani_proizvod");
        } else {
            izmeniButton.setVisible(false);
            sacuvajButton.setVisible(true);
            jtxtBrProizvoda.setEnabled(true);
            jtxtBrProizvoda.setEditable(true);
        }

    }

    private boolean validirajUnosProizvoda() {
        boolean valid = true;
        jlblNazivProizvodaValidator.setVisible(false);

        String naziv = jtxtNazivProizvoda.getText();
        if (naziv == null || naziv.isEmpty()) {
            valid = false;
            jlblNazivProizvodaValidator.setVisible(true);
        }

        String sifra = jtxtBrProizvoda.getText();
        if (sifra == null || sifra.isEmpty()) {
            valid = false;
            jlblNazivProizvodaValidator.setVisible(true);
        } else {
            try {
                Long.parseLong(sifra);
            } catch (Exception e) {
                valid = false;
                jlblNazivProizvodaValidator.setVisible(true);
            }
        }

        return valid;
    }
}
