/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package slavko.baze2.procesnabavke.gui.forme.proizvod;

import slavko.baze2.procesnabavke.gui.domen.PoslovniPartner;
import slavko.baze2.procesnabavke.gui.domen.Proizvod;
import slavko.baze2.procesnabavke.gui.forme.proizvod.model.ProizvodTableModel;
import slavko.baze2.procesnabavke.gui.forme.util.GuiUtil;
import slavko.baze2.procesnabavke.gui.forme.util.IzborProizvodaOsluškivač;
import java.awt.BorderLayout;
import java.awt.Component;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.Document;
import javax.swing.text.NumberFormatter;
import javax.swing.text.PlainDocument;
import slavko.baze2.procesnabavke.gui.poslovnalogika.Kontroler;

/**
 *
 * @author Slavko
 */
public class PanelPretragaProizvoda extends javax.swing.JPanel {

    /**
     * Creates new form PanelPretragaProizvoda
     */
    private IzborProizvodaOsluškivač izborProizvodaOsluškivač;

    public PanelPretragaProizvoda() {
        initComponents();
        srediFormu(false);
    }

    public PanelPretragaProizvoda(IzborProizvodaOsluškivač izborProizvodaOsluškivač) {
        this.izborProizvodaOsluškivač = izborProizvodaOsluškivač;
        initComponents();
        srediFormu(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnPronadjiProizvode = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblProizvodi = new javax.swing.JTable();
        jbtnDetaljiProizvod = new javax.swing.JButton();
        jbtnObrisiProizvod = new javax.swing.JButton();
        jbtnIzaberi = new javax.swing.JButton();
        jlblKoličina = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jftxtMinCena = new javax.swing.JFormattedTextField();
        jftfMaxCena = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jftfStanjeIspod = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtNazivProizvoda = new javax.swing.JTextField();
        jftxtKoličina = new javax.swing.JFormattedTextField();

        jbtnPronadjiProizvode.setText("Pronađi proizvode");
        jbtnPronadjiProizvode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPronadjiProizvodeActionPerformed(evt);
            }
        });

        jtblProizvodi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblProizvodi);

        jbtnDetaljiProizvod.setText("Detalji");
        jbtnDetaljiProizvod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDetaljiProizvodActionPerformed(evt);
            }
        });

        jbtnObrisiProizvod.setText("Obriši proizvod");
        jbtnObrisiProizvod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiProizvodActionPerformed(evt);
            }
        });

        jbtnIzaberi.setText("Izaberi");
        jbtnIzaberi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzaberiActionPerformed(evt);
            }
        });

        jlblKoličina.setText("Količina:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Kriterijumi pretrage"));

        jLabel4.setText("Stanje ispod:");

        jLabel1.setText("Naziv proizvoda: ");

        jLabel2.setText("Minimalna cena:");

        jLabel3.setText("Maksimalna cena:");

        jtxtNazivProizvoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNazivProizvodaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftfStanjeIspod))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtNazivProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jftxtMinCena, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftfMaxCena, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtNazivProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jftfStanjeIspod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jftxtMinCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jftfMaxCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jlblKoličina, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jftxtKoličina, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jbtnIzaberi, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnDetaljiProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnObrisiProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 413, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnPronadjiProizvode, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(288, 288, 288))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnPronadjiProizvode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDetaljiProizvod)
                    .addComponent(jbtnObrisiProizvod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblKoličina)
                    .addComponent(jftxtKoličina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnIzaberi)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPronadjiProizvodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPronadjiProizvodeActionPerformed
        String naziv = jtxtNazivProizvoda.getText();
        String minCena = jftxtMinCena.getText();
        String maxCena = jftfMaxCena.getText();
        String stanjeIspod = jftfStanjeIspod.getText();

        Double minCenaDouble = null;
        if (minCena != null && !minCena.isEmpty()) {
            minCenaDouble = Double.parseDouble(minCena.replace(",", ""));
        }
        Double maxCenaDouble = null;
        if (maxCena != null && !maxCena.isEmpty()) {
            maxCenaDouble = Double.parseDouble(maxCena.replace(",", ""));
        }
        Double stanjeIspodDouble = null;
        if (stanjeIspod != null && !stanjeIspod.isEmpty()) {
            stanjeIspodDouble = Double.parseDouble(stanjeIspod.replace(",", ""));
        }

        try {
            List<Proizvod> sviProizvodi = new ArrayList<>();
            List<Proizvod> filtriraniProizvodi = new ArrayList<>();
            sviProizvodi = Kontroler.vratiInstancu().vratiProizvode();
            for (Proizvod p : sviProizvodi) {
                if (naziv != null && !naziv.isEmpty()) {
                    if (!p.getNaziv().contains(naziv)) {
                        continue;
                    }
                }
                if (minCenaDouble != null) {
                    if (!(p.getCenaBezPDVa() >= minCenaDouble)) {
                        continue;
                    }
                }
                if (maxCenaDouble != null) {
                    if (!(p.getCenaBezPDVa() <= maxCenaDouble)) {
                        continue;
                    }
                }
                if (stanjeIspodDouble != null) {
                    if (!(p.getStanje() < stanjeIspodDouble)) {
                        continue;
                    }
                }
                filtriraniProizvodi.add(p);
            }
            ProizvodTableModel ptm = ((ProizvodTableModel) jtblProizvodi.getModel());
            ptm.postaviProizvode(filtriraniProizvodi);
            if(filtriraniProizvodi.isEmpty()){
                JOptionPane.showMessageDialog(this, "Sistem ne može da nadje proizvode po zadatim vrednostima", "Greška", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }

        jftfMaxCena.setValue(null);
        jftxtMinCena.setValue(null);
        jftfStanjeIspod.setValue(null);


    }//GEN-LAST:event_jbtnPronadjiProizvodeActionPerformed

    private void jbtnDetaljiProizvodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDetaljiProizvodActionPerformed
         if (jtblProizvodi.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Morate selektovati proizvod u tabeli!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        slavko.baze2.procesnabavke.gui.util.Util.vratiInstancu().postavi("izabrani_proizvod", ((ProizvodTableModel) jtblProizvodi.getModel()).getProizvod(jtblProizvodi.getSelectedRow()));
        JDialog dialog = new JDialog((JDialog) SwingUtilities.getWindowAncestor(this), "Izmena proizvoda", true);
        dialog.setLayout(new BorderLayout());
        dialog.add(new PanelRadSaProizvodom(), BorderLayout.CENTER);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_jbtnDetaljiProizvodActionPerformed

    private void jtxtNazivProizvodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNazivProizvodaActionPerformed
        
    }//GEN-LAST:event_jtxtNazivProizvodaActionPerformed

    private void jbtnIzaberiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzaberiActionPerformed
        if (jtblProizvodi.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Morate selektovati proizvod u tabeli!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String količina = jftxtKoličina.getText();
        int količinaInt = Integer.parseInt(količina);
        Proizvod proizvod = ((ProizvodTableModel) jtblProizvodi.getModel()).getProizvod(jtblProizvodi.getSelectedRow());
        izborProizvodaOsluškivač.proizvodIzabran(proizvod, količinaInt);
        ((JDialog) SwingUtilities.getWindowAncestor(this)).dispose();

    }//GEN-LAST:event_jbtnIzaberiActionPerformed

    private void jbtnObrisiProizvodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiProizvodActionPerformed
        if (jtblProizvodi.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Morate selektovati proizvod u tabeli!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ProizvodTableModel ptm = ((ProizvodTableModel) jtblProizvodi.getModel());
        Proizvod proizvod = ptm.getProizvod(jtblProizvodi.getSelectedRow());
        try {
            Kontroler.vratiInstancu().obrisiProizvod(proizvod);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ptm.obrisiRed(jtblProizvodi.getSelectedRow());
        JOptionPane.showMessageDialog(this, "Sistem je obrisao proizvod", "Brisanje proizvoda", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jbtnObrisiProizvodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDetaljiProizvod;
    private javax.swing.JButton jbtnIzaberi;
    private javax.swing.JButton jbtnObrisiProizvod;
    private javax.swing.JButton jbtnPronadjiProizvode;
    private javax.swing.JFormattedTextField jftfMaxCena;
    private javax.swing.JFormattedTextField jftfStanjeIspod;
    private javax.swing.JFormattedTextField jftxtKoličina;
    private javax.swing.JFormattedTextField jftxtMinCena;
    private javax.swing.JLabel jlblKoličina;
    private javax.swing.JTable jtblProizvodi;
    private javax.swing.JTextField jtxtNazivProizvoda;
    // End of variables declaration//GEN-END:variables

    private void srediFormu(boolean samoIzbor) {
        if (samoIzbor) {
            jbtnDetaljiProizvod.setVisible(false);
            jbtnObrisiProizvod.setVisible(false);
        } else {
            jbtnIzaberi.setVisible(false);
            jftxtKoličina.setVisible(false);
            jlblKoličina.setVisible(false);
        }

        NumberFormatter formatter = new NumberFormatter(NumberFormat.getInstance());

        formatter.setMinimum(1);
        formatter.setMaximum(10000000);
        formatter.setAllowsInvalid(false);

        jftxtMinCena.setFormatterFactory(new DefaultFormatterFactory(formatter));
        jftfMaxCena.setFormatterFactory(new DefaultFormatterFactory(formatter));
        jftfStanjeIspod.setFormatterFactory(new DefaultFormatterFactory(formatter));
        jftxtKoličina.setFormatterFactory(new DefaultFormatterFactory(formatter));
        jftxtKoličina.setValue(1);

        List<Proizvod> lp = new ArrayList<>();
        try {
            lp = Kontroler.vratiInstancu().vratiProizvode();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        jtblProizvodi.setModel(new ProizvodTableModel(lp));
        GuiUtil.resizeColumnWidth(jtblProizvodi,50);
        jtblProizvodi.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    }

    

}
